version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: toko_api
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
